---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  environments_path: ./test/environments
  data_bags_path: ./test/data_bags
  client_rb:
    environment: kitchen

platforms:
  - name: centos67
    driver_config:
      box: boxcutter/centos67
    attributes:
      system:
        primary_interface: eth1
  - name: centos71
    driver_config:
      box: boxcutter/centos71
    attributes:
      system:
        primary_interface: enp0s8
  - name: centos72
    driver_config:
      box: boxcutter/centos72
    attributes:
      system:
        primary_interface: enp0s8
  - name: ubuntu1404
    driver_config:
      box: boxcutter/ubuntu1404
    attributes:
      system:
        primary_interface: eth1
  - name: ubuntu1504
    driver_config:
      box: boxcutter/ubuntu1504
    attributes:
      system:
        primary_interface: eth1
  - name: debian82
    driver_config:
      box: boxcutter/debian82
    attributes:
      system:
        primary_interface: eth1

suites:
  - name: es1
    run_list:
      - recipe[masala_elk::elastic_search]
      - recipe[masala_elk::logstash]
    driver:
      network:
      - ["private_network", {ip: "10.10.10.11"}]
      customize:
        memory: 1536
        cpus: 1
    attributes:
      system:
        short_hostname: 'es1'
        static_hosts:
          10.10.10.11: es1.kitchen.masalatest.com
          10.10.10.12: es2.kitchen.masalatest.com
          10.10.10.13: es3.kitchen.masalatest.com
      logstash:
        instance_default:
          xms: '256M'
          xmx: '256M'
      masala_elk:
        elastic_search:
          unicast_discovery_hosts: ["10.10.10.11", "10.10.10.12", "10.10.10.13"]
        logstash:
          input:
            es_logs:
              plugin: 'file'
              vars:
                path: '/elasticsearch/logs/*'
                type: 'es'
            ls_logs:
              plugin: 'file'
              vars:
                path: '/opt/logstash/server/log/logstash.log'
                type: 'ls'
          output:
            stdout:
              plugin: 'stdout'
            es_es:
              plugin: 'elasticsearch'
              only_type: 'es'
              vars:
                hosts: ["10.10.10.11:9200"]
                index: 'es-%{+YYYY.MM.dd}'
            es_ls:
              plugin: 'elasticsearch'
              only_type: 'ls'
              vars:
                hosts: ["10.10.10.11:9200"]
                index: 'ls-%{+YYYY.MM.dd}'
  - name: es2
    run_list:
      - recipe[masala_elk::elastic_search]
      - recipe[masala_elk::logstash]
    driver:
      network:
      - ["private_network", {ip: "10.10.10.12"}]
      customize:
        memory: 1536
        cpus: 1
    attributes:
      system:
        short_hostname: 'es2'
        static_hosts:
          10.10.10.11: es1.kitchen.masalatest.com
          10.10.10.12: es2.kitchen.masalatest.com
          10.10.10.13: es3.kitchen.masalatest.com
      logstash:
        instance_default:
          xms: '256M'
          xmx: '256M'
      masala_elk:
        elastic_search:
          unicast_discovery_hosts: ["10.10.10.11", "10.10.10.12", "10.10.10.13"]
        logstash:
          input:
            es_logs:
              plugin: 'file'
              vars:
                path: '/elasticsearch/logs/*'
                type: 'es'
            ls_logs:
              plugin: 'file'
              vars:
                path: '/opt/logstash/server/log/logstash.log'
                type: 'ls'
          output:
            stdout:
              plugin: 'stdout'
            es_es:
              plugin: 'elasticsearch'
              only_type: 'es'
              vars:
                hosts: ["10.10.10.12:9200"]
                index: 'es-%{+YYYY.MM.dd}'
            es_ls:
              plugin: 'elasticsearch'
              only_type: 'ls'
              vars:
                hosts: ["10.10.10.12:9200"]
                index: 'ls-%{+YYYY.MM.dd}'
  - name: es3
    run_list:
      - recipe[masala_elk::elastic_search]
      - recipe[masala_elk::logstash]
      - recipe[masala_elk::kibana]
    driver:
      network:
      - ["private_network", {ip: "10.10.10.13"}]
      customize:
        memory: 1536
        cpus: 1
    attributes:
      system:
        short_hostname: 'es3'
        static_hosts:
          10.10.10.11: es1.kitchen.masalatest.com
          10.10.10.12: es2.kitchen.masalatest.com
          10.10.10.13: es3.kitchen.masalatest.com
      logstash:
        instance_default:
          xms: '256M'
          xmx: '256M'
      masala_elk:
        elastic_search:
          unicast_discovery_hosts: ["10.10.10.11", "10.10.10.12", "10.10.10.13"]
        logstash:
          input:
            es_logs:
              plugin: 'file'
              vars:
                path: '/elasticsearch/logs/*'
                type: 'es'
            ls_logs:
              plugin: 'file'
              vars:
                path: '/opt/logstash/server/log/logstash.log'
                type: 'ls'
          output:
            stdout:
              plugin: 'stdout'
            es_es:
              plugin: 'elasticsearch'
              only_type: 'es'
              vars:
                hosts: ["10.10.10.13:9200"]
                index: 'es-%{+YYYY.MM.dd}'
            es_ls:
              plugin: 'elasticsearch'
              only_type: 'ls'
              vars:
                hosts: ["10.10.10.13:9200"]
                index: 'ls-%{+YYYY.MM.dd}'
      kibana:
        elasticsearch:
          server: 'http://10.10.10.13:9200'
